[[main]]
none = "none"

[[main]]
name = "Handouts"
pageRef = "handouts"
identifier = "QPIB9CQXmW"
weight = 9999

[[main]]
name = "Competitions"
pageRef = "competitions"
identifier = "WL0LBr3Dhm"
weight = 9999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "aPs7fdop9o"
weight = 9999

[[footer]]
none = "none"
